In [6]:
import csv
import pandas as pd

In [7]:
def get_game_score(f_name, ID):
    """
    if line[1] == gameID:
        print(line[0:10], line[16])

        if line[22] == "1":
            scores[line[16]] += 6
        if line[23] == "Made":
            scores[line[16]] += 1
        if line[24] != "Good":
            scores[line[16]] += 2
        if line[54] == "Good":
            scores[line[16]] += 3
    """


def filter_game(row, *args):
    gameID = args[0]

    if row[1] == gameID:
        print(row[71], row[72])


""" 
call 'func' on each row in the data set.
Enumerates the header fields as well.  
"""
def iter_csv(f_name, func, *args, **kargs):
    with open(f_name, "r") as f:
        reader = csv.reader(f)

        # - enumerate the header indices
        for i, header in enumerate(next(reader)):
            print(i, header, end=", ")
        print("\n")

        for line in reader:
            if args and kargs:
                func(line, *args, **kargs)
            elif args:
                func(line, *args)
            elif kargs:
                func(line, **kargs)
            else:
                func(line)

In [11]:


""" 
Data cleaning ideas and some EDA, we need 10 in total for each
   * We will need to drop certain columns 
      
   * Organize players by team (EDA)
   
   * Organize players by position (EDA)
   
   * Combine the two data sets
   
   * Filter only games from 2017 - 2018 (playoffs)
 
   * Map abbreviated team names to actual team names 
   
   * Need to filter drives where a score occurs 
   
   * we will need to create a way of actually calculating if a team won or not 
     this is done by adding up all scores for each time. IDK if this is cleaning or EDA,
     but im leaning more towards cleaning
   
   * lots of data is un-formatted this will probably be 
     3 to 5 steps on its own.  
              
"""

df = pd.read_csv(r'datasets/Salary/NFL_2017_Player_Salaries.csv')
df_active = pd.read_csv(r'datasets/Salary/NFL_2018_Active_Team_Rosters.csv')

In [12]:
df

      index   Rk            Player Pos   Tm     Cap Hit
0         0  1.0      Kirk Cousins  QB  WAS  23943600.0
1         1  2.0  Trumaine Johnson  CB  LAR  16742400.0
2         2  3.0       Josh Norman  CB  WAS  16500000.0
3         3  NaN        Von Miller  LB  DEN  16500000.0
4         4  5.0    Justin Houston  LB  KAN  16350000.0
...     ...  ...               ...  ..  ...         ...
1994   1994  NaN   Derrick Mathews  LB  NYG     27353.0
1995   1995  NaN     Rickey Hatley  DT  BUF     27353.0
1996   1996  NaN      Emanuel Byrd  TE  GNB     27353.0
1997   1997  NaN       Aaron Neary   C  LAR     27353.0
1998   1998  NaN   Garrett Sickels  DE  LAR     27353.0

[1999 rows x 6 columns]

In [13]:
df_plays = pd.read_csv(r'datasets/PlayByPlay/NFL Play by Play 2009-2018 (v5).csv')
#df_active = pd.read_csv(r'datasets/Salary/NFL_2018_Active_Team_Rosters.csv')

/var/folders/_2/zt8h8ycx35j67c540bwphrxc0000gn/T/ipykernel_9787/2704961152.py:1: DtypeWarning: Columns (42,166,167,168,169,174,175,178,179,182,183,188,189,190,191,194,195,203,204,205,218,219,220,231,232,233,238,240,241,249) have mixed types. Specify dtype option on import or set low_memory=False.
  df_plays = pd.read_csv(r'datasets/PlayByPlay/NFL Play by Play 2009-2018 (v5).csv')

In [14]:
df_plays

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449366,4059,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
449367,4081,2018121700,CAR,NO,CAR,home,NO,CAR,66.0,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
449368,4106,2018121700,CAR,NO,CAR,home,NO,CAR,61.0,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
449369,4128,2018121700,CAR,NO,NO,away,CAR,CAR,39.0,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
449370,4150,2018121700,CAR,NO,NaN,NaN,NaN,CAR,NaN,2018-12-17,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN